#!/usr/bin/env bash
# BASE-01 Phase 4: matched-shape operator comparison at M = 128/512/1024/2048/4096.
# Uses llama-bench -p <M> to drive real-model activations at those prompt lengths
# (n_gen=0). The per-op profile hook (GGML_OP_PROFILE for IQ3, ESCHA_PROFILE for
# ESCHA) provides per-projection times at each depth. Synthetic-only results are
# labeled diagnostic. Attribution only (graphs off).
set -uo pipefail
REPO="/mnt/d/CODEX WORKSPACE/beellama-escha"
BENCH_P="$REPO/build-cuda-base01-profile/bin/llama-bench"
BENCH_C="$REPO/build-cuda-base01/bin/llama-bench"
IDS="/mnt/d/CODEX WORKSPACE/escha-w2-lowgpu/evidence/P-ARCH-05/2026-08-29/escha-controlled-server-002/shared-2048.ids"
MODEL_A="/mnt/d/CODEX WORKSPACE/escha-w2-lowgpu/weights/escha-w2-lowgpu-mono-parity.gguf"
MODEL_B="/mnt/d/CODEX WORKSPACE/beellama-release/models/Qwen3.8-27B-LowGPU-NoMTP-IQ3XXXS.gguf"
OUT="${1:-$REPO/evidence/BASE-01-escha-vs-iq3xxxs/2026-09-01/operators}"
mkdir -p "$OUT"
export PATH="/usr/lib/wsl/lib:$PATH"
COMMON=(-n 0 -ngl 99 -b 2048 -ub 2048 -ctk f16 -ctv f16 -fa on -r 1 -o json -oe json)
IDS="/mnt/d/CODEX WORKSPACE/escha-w2-lowgpu/evidence/P-ARCH-05/2026-08-29/escha-controlled-server-002/shared-2048.ids"
# Per-depth ID files (prefixes of the canonical shared 2048 IDs; 4096 = doubled
# prefix) so -p M matches the actual prompt length. Generated by the operator
# harness; stored in the operators dir.
DEPTH_IDS="$OUT/ids-%d.txt"

for M in 128 512 1024 2048 4096; do
  echo "=== M=$M ==="
  IDS_ARG=(--prompt-tokens-file "$(printf "$DEPTH_IDS" "$M")")
  # ESCHA profile (ESCHA_PROFILE hook, profile build)
  GGML_CUDA_DISABLE_GRAPHS=1 ESCHA_PROFILE=1 "$BENCH_P" -m "$MODEL_A" "${IDS_ARG[@]}" -p "$M" "${COMMON[@]}" \
    >"$OUT/A-escha-M$M.json" 2>"$OUT/A-escha-M$M.profile.stderr"
  # ESCHA canonical total at M (control build, no hooks)
  GGML_CUDA_DISABLE_GRAPHS=1 "$BENCH_C" -m "$MODEL_A" "${IDS_ARG[@]}" -p "$M" "${COMMON[@]}" \
    >"$OUT/A-escha-M$M.total.json" 2>"$OUT/A-escha-M$M.total.stderr"
  # IQ3 op-profile (GGML_OP_PROFILE hook, profile build)
  GGML_CUDA_DISABLE_GRAPHS=1 GGML_OP_PROFILE=1 "$BENCH_P" -m "$MODEL_B" "${IDS_ARG[@]}" -p "$M" "${COMMON[@]}" \
    >"$OUT/B-iq3-M$M.json" 2>"$OUT/B-iq3-M$M.op_profile.stderr"
  # IQ3 canonical total at M (control build)
  GGML_CUDA_DISABLE_GRAPHS=1 "$BENCH_C" -m "$MODEL_B" "${IDS_ARG[@]}" -p "$M" "${COMMON[@]}" \
    >"$OUT/B-iq3-M$M.total.json" 2>"$OUT/B-iq3-M$M.total.stderr"
  /usr/lib/wsl/lib/nvidia-smi --query-gpu=clocks.sm,clocks.mem,temperature.gpu,power.draw --format=csv,noheader | tee -a "$OUT/clocks.log"
done
echo "PHASE 4 COMPLETE"
